language: java

sudo: false

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

script: mvn verify

after_success:
  - mvn coveralls:report

cache:
  directories:
    - '$HOME/.m2/repository'
